import Pgx.IR.Json

/-!
# PostgreSQL contract compatibility comparison

The `pg_compat_test` action supplies snapshots generated by two PostgreSQL
majors.  Server major is intentionally excluded from `compatibilityHash`; all
other type-relevant normalized semantics remain part of the comparison.
-/

namespace Pgx.Codegen.Compare

/-- Compatibility is equality of the major-independent semantic hashes. -/
def compatible (left right : Pgx.DatabaseIR) : Bool :=
  left.compatibilityHash == right.compatibilityHash

private def readSnapshot (path : String) : IO (Except String Pgx.DatabaseIR) := do
  try
    let document ← IO.FS.readFile path
    match Pgx.DatabaseIR.parseSnapshot document with
    | .ok database => pure (.ok database)
    | .error error => pure (.error s!"cannot parse snapshot '{path}': {error}")
  catch error =>
    pure (.error s!"cannot read snapshot '{path}': {error}")

private def reportInputError (error : String) : IO UInt32 := do
  IO.eprintln s!"lean-pgx compatibility comparison failed: {error}"
  pure 2

def run (leftPath rightPath : String) : IO UInt32 := do
  let left ← match ← readSnapshot leftPath with
    | .ok database => pure database
    | .error error => return ← reportInputError error
  let right ← match ← readSnapshot rightPath with
    | .ok database => pure database
    | .error error => return ← reportInputError error
  let leftHash := left.compatibilityHash
  let rightHash := right.compatibilityHash
  if leftHash == rightHash then
    pure 0
  else
    IO.eprintln "lean-pgx PostgreSQL compatibility mismatch:"
    IO.eprintln s!"  {leftPath} (PostgreSQL {left.serverMajor}): {leftHash}"
    IO.eprintln s!"  {rightPath} (PostgreSQL {right.serverMajor}): {rightHash}"
    pure 1

def main : List String → IO UInt32
  | [leftPath, rightPath] => run leftPath rightPath
  | arguments => do
      IO.eprintln s!"lean-pgx compatibility comparison expects exactly two \
        .pgir.json paths, received {arguments.length}"
      IO.eprintln "usage: pgx_compat_compare LEFT.pgir.json RIGHT.pgir.json"
      pure 2

end Pgx.Codegen.Compare

def main (arguments : List String) : IO UInt32 :=
  Pgx.Codegen.Compare.main arguments
