import Pgx.Codegen.ConstraintParser
import Pgx.Codegen.Identifier
import Pgx.Codegen.Projection
import Pgx.Constraint.Semantics
import Pgx.TypeMapping
import Pgx.Typed

/-!
# Pure Lean source emission

`emitDatabase` is deliberately independent of the filesystem and PostgreSQL.
It validates a normalized `DatabaseIR` and returns every declared generated
source as data.  The build rule is responsible only for writing those values
to its declared outputs.
-/

namespace Pgx.Codegen

open Pgx.Codegen.Identifier

inductive CodegenError where
  | invalidModulePrefix (value reason : String)
  | malformedIR (context reason : String)
  | duplicateType (key : Pgx.TypeKey)
  | duplicateRelation (key : Pgx.RelationKey)
  | duplicateQuery (name : String)
  | unsupportedType (key : Pgx.TypeKey) (context : String)
  | unsupportedConstraint (context reason : String)
  | cyclicDomain (key : Pgx.TypeKey)
  deriving Repr, BEq, Inhabited

namespace CodegenError

def toMessage : CodegenError → String
  | .invalidModulePrefix value reason =>
      s!"invalid generated module prefix {repr value}: {reason}"
  | .malformedIR context reason => s!"invalid {context}: {reason}"
  | .duplicateType key => s!"duplicate PostgreSQL type in generation IR: {key}"
  | .duplicateRelation key => s!"duplicate PostgreSQL relation in generation IR: {key}"
  | .duplicateQuery name => s!"duplicate generated query name: {name}"
  | .unsupportedType key context =>
      s!"unsupported PostgreSQL type {key} while generating {context}"
  | .unsupportedConstraint context reason =>
      s!"unsupported local constraint while generating {context}: {reason}"
  | .cyclicDomain key => s!"cyclic PostgreSQL domain base chain at {key}"

end CodegenError

instance : ToString CodegenError := ⟨CodegenError.toMessage⟩

/-- One generated Lean module and its repository-relative output path. -/
structure GeneratedSource where
  path : String
  moduleName : String
  contents : String
  deriving Repr, BEq, Inhabited

/-- The fixed generated output partition.  Query modules vary only with the
declared query inputs; catalog-discovered objects remain in the three fixed
schema modules. -/
structure GeneratedSources where
  modulePrefix : String
  types : GeneratedSource
  schema : GeneratedSource
  constraints : GeneratedSource
  queries : Array GeneratedSource
  root : GeneratedSource
  deriving Repr, BEq, Inhabited

namespace GeneratedSources

def all (sources : GeneratedSources) : Array GeneratedSource :=
  #[sources.types, sources.schema, sources.constraints] ++ sources.queries ++ #[sources.root]

def findModule? (sources : GeneratedSources) (moduleName : String) : Option GeneratedSource :=
  sources.all.find? (fun source => source.moduleName == moduleName)

end GeneratedSources

private structure NamedType where
  key : Pgx.TypeKey
  leanType : String
  codec : String

private structure NamedSchema where
  source : String
  leanName : String

private structure NamedRelation where
  key : Pgx.RelationKey
  schemaName : String
  relationName : String

private structure NamedQuery where
  query : Pgx.QueryIR
  moduleName : String

private structure NamingPlan where
  modulePrefix : String
  prefixPath : String
  types : Array NamedType
  schemas : Array NamedSchema
  relations : Array NamedRelation
  queries : Array NamedQuery

private structure TypeUse where
  leanType : String
  codec : Option String := none

private def generatedHeader : String :=
  "/- This file is generated by lean-pgx.  Do not edit it directly. -/"

private def sourceText (lines : List String) : String :=
  String.intercalate "\n" lines ++ "\n"

private def commaSep (values : Array String) : String :=
  String.intercalate ", " values.toList

private def arrayExpr (values : Array String) : String :=
  "#[" ++ commaSep values ++ "]"

private def recordExpr (body : String) : String :=
  "{ " ++ body ++ " }"

private def optionExpr (value : Option String) : String :=
  match value with
  | none => "none"
  | some value => "some (" ++ value ++ ")"

private def boolExpr (value : Bool) : String :=
  if value then "true" else "false"

private def sortStrings (values : Array String) : Array String :=
  values.toList.mergeSort (fun left right => compare left right == .lt) |>.toArray

private def sortTypeKeys (values : Array Pgx.TypeKey) : Array Pgx.TypeKey :=
  values.toList.mergeSort (fun left right =>
    compare left.display right.display == .lt) |>.toArray

private def pushUnique [BEq α] (values : Array α) (value : α) : Array α :=
  if values.contains value then values else values.push value

private def firstDuplicateList? [BEq α] : List α → Option α
  | [] => none
  | value :: rest => if rest.contains value then some value else firstDuplicateList? rest

private def firstDuplicate? [BEq α] (values : Array α) : Option α :=
  firstDuplicateList? values.toList

private def normalizePrefix (value : String) : Except CodegenError (String × String) := do
  if value.isEmpty then
    throw (.invalidModulePrefix value "the prefix is empty")
  let components := value.splitOn "."
  if components.any String.isEmpty then
    throw (.invalidModulePrefix value "empty dot-separated component")
  let components := components.map (fun component => upperCamel component "Generated")
  pure (String.intercalate "." components, String.intercalate "/" components)

private def typeKeyExpr (key : Pgx.TypeKey) : String :=
  recordExpr s!"schema := {stringLiteral key.schema}, name := {stringLiteral key.name}, kind := .{key.kind.tag}"

private def typeRefExpr (ref : Pgx.TypeRef) : String :=
  let typmod := ref.typmod.map (fun value => toString value)
  recordExpr s!"key := {typeKeyExpr ref.key}, typmod := {optionExpr typmod}"

private def relationKeyExpr (key : Pgx.RelationKey) : String :=
  recordExpr s!"schema := {stringLiteral key.schema}, name := {stringLiteral key.name}"

private def columnKeyExpr (key : Pgx.ColumnKey) : String :=
  recordExpr s!"relation := {relationKeyExpr key.relation}, name := {stringLiteral key.name}"

private def collationKeyExpr (key : Pgx.CollationKey) : String :=
  recordExpr s!"schema := {stringLiteral key.schema}, name := {stringLiteral key.name}"

private def typeDescExpr (db : Pgx.DatabaseIR) (key : Pgx.TypeKey) : String :=
  match db.enum? key with
  | some value =>
      let labels := arrayExpr (value.labels.map stringLiteral)
      recordExpr s!"key := {typeKeyExpr key}, enumLabels := {labels}"
  | none =>
      match db.domain? key with
      | some value =>
          recordExpr s!"key := {typeKeyExpr key}, base := some ({typeRefExpr value.base}), notNull := {boolExpr value.notNull}"
      | none => recordExpr s!"key := {typeKeyExpr key}"

private def sessionExpr (session : Pgx.SessionContract) : String :=
  let searchPath := arrayExpr (session.searchPath.map stringLiteral)
  recordExpr s!"searchPath := {searchPath}, timezone := {stringLiteral session.timezone}, encoding := {stringLiteral session.encoding}, standardConformingStrings := {boolExpr session.standardConformingStrings}"

private def staticColumnExpr (column : Pgx.RelationColumnIR) : String :=
  recordExpr s!"name := {stringLiteral column.name}, ordinal := {column.ordinal}, ty := {typeRefExpr column.ty}, nullable := {boolExpr column.nullable}"

private def relationKindExpr : Pgx.RelationKind → String
  | .table => "table"
  | .partitionedTable => "partitionedTable"
  | .view => "view"
  | .materializedView => "materializedView"
  | .foreignTable => "foreignTable"

private def staticRelationExpr (relation : Pgx.RelationIR) : String :=
  let columns := arrayExpr (relation.columns.map staticColumnExpr)
  recordExpr s!"key := {relationKeyExpr relation.key}, kind := .{relationKindExpr relation.kind}, columns := {columns}"

private def constraintKindExpr : Pgx.ConstraintKind → String
  | .check => "check"
  | .notNull => "notNull"
  | .primaryKey => "primaryKey"
  | .unique => "unique"
  | .foreignKey => "foreignKey"
  | .exclusion => "exclusion"

private def scalarKindExpr : Pgx.Constraint.ScalarKind → String
  | .boolean => "Pgx.Constraint.ScalarKind.boolean"
  | .int16 => "Pgx.Constraint.ScalarKind.int16"
  | .int32 => "Pgx.Constraint.ScalarKind.int32"
  | .int64 => "Pgx.Constraint.ScalarKind.int64"
  | .numeric => "Pgx.Constraint.ScalarKind.numeric"
  | .text => "Pgx.Constraint.ScalarKind.text"
  | .enumeration key =>
      "Pgx.Constraint.ScalarKind.enumeration (" ++ typeKeyExpr key ++ ")"

private def scalarTypeExpr (ty : Pgx.Constraint.ScalarType) : String :=
  recordExpr s!"declared := {typeRefExpr ty.declared}, base := {scalarKindExpr ty.base}, domains := {arrayExpr (ty.domains.map typeKeyExpr)}"

private def literalExpr : Pgx.Constraint.Literal → String
  | .null => "Pgx.Constraint.Literal.null"
  | .boolean value => s!"Pgx.Constraint.Literal.boolean {boolExpr value}"
  | .integer value => s!"Pgx.Constraint.Literal.integer ({value})"
  | .numeric value => s!"Pgx.Constraint.Literal.numeric {stringLiteral value}"
  | .text value => s!"Pgx.Constraint.Literal.text {stringLiteral value}"
  | .enumeration key label =>
      s!"Pgx.Constraint.Literal.enumeration ({typeKeyExpr key}) {stringLiteral label}"

private def castPreservationExpr : Pgx.Constraint.CastPreservation → String
  | .identity => "identity"
  | .domain => "domain"
  | .integerWiden => "integerWiden"
  | .exactNumeric => "exactNumeric"
  | .textRepresentation => "textRepresentation"
  | .enumLiteral => "enumLiteral"

private partial def valueExprExpr : Pgx.Constraint.ValueExpr → String
  | .column name ty nullable =>
      s!"Pgx.Constraint.ValueExpr.column {stringLiteral name} ({scalarTypeExpr ty}) {boolExpr nullable}"
  | .domainValue ty nullable =>
      s!"Pgx.Constraint.ValueExpr.domainValue ({scalarTypeExpr ty}) {boolExpr nullable}"
  | .literal value ty =>
      s!"Pgx.Constraint.ValueExpr.literal ({literalExpr value}) ({scalarTypeExpr ty})"
  | .cast preservation value target =>
      s!"Pgx.Constraint.ValueExpr.cast .{castPreservationExpr preservation} ({valueExprExpr value}) ({scalarTypeExpr target})"
  | .neg value result =>
      s!"Pgx.Constraint.ValueExpr.neg ({valueExprExpr value}) ({scalarTypeExpr result})"
  | .add left right result =>
      s!"Pgx.Constraint.ValueExpr.add ({valueExprExpr left}) ({valueExprExpr right}) ({scalarTypeExpr result})"
  | .sub left right result =>
      s!"Pgx.Constraint.ValueExpr.sub ({valueExprExpr left}) ({valueExprExpr right}) ({scalarTypeExpr result})"
  | .charLength value result =>
      s!"Pgx.Constraint.ValueExpr.charLength ({valueExprExpr value}) ({scalarTypeExpr result})"
  | .btrim value result =>
      s!"Pgx.Constraint.ValueExpr.btrim ({valueExprExpr value}) ({scalarTypeExpr result})"
  | .position substring string result =>
      s!"Pgx.Constraint.ValueExpr.position ({valueExprExpr substring}) ({valueExprExpr string}) ({scalarTypeExpr result})"

private def comparisonExprName : Pgx.Constraint.Comparison → String
  | .eq => "eq"
  | .ne => "ne"
  | .lt => "lt"
  | .le => "le"
  | .gt => "gt"
  | .ge => "ge"

private partial def truthExprExpr : Pgx.Constraint.TruthExpr → String
  | .constant value =>
      let value := optionExpr (value.map boolExpr)
      s!"Pgx.Constraint.TruthExpr.constant {value}"
  | .fromBoolean value =>
      s!"Pgx.Constraint.TruthExpr.fromBoolean ({valueExprExpr value})"
  | .compare operator left right =>
      s!"Pgx.Constraint.TruthExpr.compare .{comparisonExprName operator} ({valueExprExpr left}) ({valueExprExpr right})"
  | .isNull value => s!"Pgx.Constraint.TruthExpr.isNull ({valueExprExpr value})"
  | .isNotNull value => s!"Pgx.Constraint.TruthExpr.isNotNull ({valueExprExpr value})"
  | .and left right =>
      s!"Pgx.Constraint.TruthExpr.and ({truthExprExpr left}) ({truthExprExpr right})"
  | .or left right =>
      s!"Pgx.Constraint.TruthExpr.or ({truthExprExpr left}) ({truthExprExpr right})"
  | .not value => s!"Pgx.Constraint.TruthExpr.not ({truthExprExpr value})"

private def constraintExpr (constraint : Pgx.ConstraintIR) : String :=
  let columns := arrayExpr (constraint.columns.map stringLiteral)
  let referencedRelation := optionExpr (constraint.referencedRelation.map relationKeyExpr)
  let referencedColumns := arrayExpr (constraint.referencedColumns.map stringLiteral)
  let expression := optionExpr (constraint.expression.map stringLiteral)
  let localExpression := optionExpr (constraint.localExpression.map truthExprExpr)
  recordExpr s!"relation := {relationKeyExpr constraint.relation}, name := {stringLiteral constraint.name}, kind := .{constraintKindExpr constraint.kind}, columns := {columns}, referencedRelation := {referencedRelation}, referencedColumns := {referencedColumns}, expression := {expression}, localExpression := {localExpression}, validated := {boolExpr constraint.validated}"

private def indexExpr (index : Pgx.IndexIR) : String :=
  let columns := arrayExpr (index.columns.map stringLiteral)
  let predicate := optionExpr (index.predicate.map stringLiteral)
  let expression := optionExpr (index.expression.map stringLiteral)
  recordExpr s!"relation := {relationKeyExpr index.relation}, name := {stringLiteral index.name}, unique := {boolExpr index.unique}, primary := {boolExpr index.primary}, valid := {boolExpr index.valid}, columns := {columns}, predicate := {predicate}, expression := {expression}"

private def paramSpecExpr (param : Pgx.ParamIR) : String :=
  recordExpr s!"name := {stringLiteral param.name}, ty := {typeRefExpr param.ty}, nullable := {boolExpr param.nullable}"

private def columnSpecExpr (column : Pgx.QueryColumnIR) : String :=
  let origin := optionExpr (column.origin.map columnKeyExpr)
  recordExpr s!"name := {stringLiteral column.name}, ty := {typeRefExpr column.ty}, nullable := {boolExpr column.nullable}, origin := {origin}"

private def checkOverride (value : Pgx.TypeOverrideIR) : Except CodegenError Unit := do
  if value.leanType.trimAscii.toString.isEmpty then
    throw (.malformedIR s!"type override {value.key}" "Lean type declaration is empty")
  if value.codec.trimAscii.toString.isEmpty then
    throw (.malformedIR s!"type override {value.key}" "codec declaration is empty")
  match value.importModule with
  | none => pure ()
  | some moduleName =>
      if moduleName.isEmpty || moduleName.trimAscii.toString != moduleName then
        throw (.malformedIR s!"type override {value.key}"
          "import module is empty or contains surrounding whitespace")

private def checkTypeSupportedAux (db : Pgx.DatabaseIR) (key : Pgx.TypeKey)
    (context : String) (seen : Array Pgx.TypeKey) : Nat → Except CodegenError Unit
  | 0 => throw (.cyclicDomain key)
  | fuel + 1 => do
  if seen.contains key then throw (.cyclicDomain key)
  match db.typeOverride? key with
  | some value => checkOverride value
  | none =>
      match Pgx.builtinTypeMapping? key with
      | some _ => pure ()
      | none =>
          match db.enum? key with
          | some _ => pure ()
          | none =>
              match db.domain? key with
              | some domain => checkTypeSupportedAux db domain.base.key context (seen.push key) fuel
              | none => throw (.unsupportedType key context)

private def checkTypeSupported (db : Pgx.DatabaseIR) (key : Pgx.TypeKey)
    (context : String) : Except CodegenError Unit :=
  checkTypeSupportedAux db key context #[] (db.domains.size + 1)

private def relation? (db : Pgx.DatabaseIR) (key : Pgx.RelationKey) :
    Option Pgx.RelationIR :=
  db.relations.find? (fun relation => relation.key == key)

private partial def wireBaseRefAux (db : Pgx.DatabaseIR) (ref : Pgx.TypeRef)
    (seen : Array Pgx.TypeKey) : Except CodegenError Pgx.TypeRef := do
  if seen.contains ref.key then throw (.cyclicDomain ref.key)
  match db.domain? ref.key with
  | none => pure ref
  | some domain => wireBaseRefAux db domain.base (seen.push ref.key)

private def wireBaseRef (db : Pgx.DatabaseIR) (ref : Pgx.TypeRef) :
    Except CodegenError Pgx.TypeRef :=
  wireBaseRefAux db ref #[]

private def validateRefinementTypmod (db : Pgx.DatabaseIR) (ref : Pgx.TypeRef)
    (context : String) :
    Except CodegenError Unit := do
  if ref.key.schema == "pg_catalog" &&
      (ref.key.name == "varchar" || ref.key.name == "bpchar") then
    if ref.typmod.isSome && (db.typeOverride? ref.key).isSome then
      throw (.unsupportedConstraint context
        s!"type override {ref.key} has no character-typmod refinement adapter")
    match Pgx.Constraint.decodeCharacterTypmod ref.typmod with
    | .ok _ => pure ()
    | .error error => throw (.malformedIR context (toString error))
  else if ref.key.schema == "pg_catalog" && ref.key.name == "numeric" &&
      ref.typmod.isSome then
    throw (.unsupportedConstraint context
      (toString (Pgx.Constraint.unsupportedNumericTypmod ref.typmod)))

private def validateDomainConstraints (db : Pgx.DatabaseIR)
    (domain : Pgx.DomainIR) : Except CodegenError Unit := do
  if (db.typeOverride? domain.key).isSome &&
      (domain.notNull || !domain.localConstraints.isEmpty || domain.base.typmod.isSome) then
    throw (.unsupportedConstraint s!"domain {domain.key}"
      "a constrained type override requires an explicit refinement adapter")
  let raw := sortStrings domain.constraints
  let typed := sortStrings (domain.localConstraints.map (·.source))
  unless raw == typed do
    throw (.malformedIR s!"domain {domain.key}"
      "raw and typed local constraint definitions differ")
  for constraint in domain.localConstraints do
    match Pgx.Codegen.ConstraintParser.parseDomainCheck domain db.enums db.domains
        constraint.source with
    | .error diagnostic =>
        throw (.unsupportedConstraint s!"domain {domain.key} constraint {constraint.name}"
          (toString diagnostic))
    | .ok parsed =>
        unless parsed.validated == constraint.validated do
          throw (.malformedIR s!"domain {domain.key} constraint {constraint.name}"
            "NOT VALID suffix differs from catalog validation metadata")
        unless parsed.expression == constraint.expression do
          throw (.malformedIR s!"domain {domain.key} constraint {constraint.name}"
            "typed expression differs from reparsing its normalized source")

private def validateRelationConstraints (db : Pgx.DatabaseIR) :
    Except CodegenError Unit := do
  for constraint in db.constraints do
    let some relation := relation? db constraint.relation
      | throw (.malformedIR s!"constraint {constraint.name}"
          s!"relation {constraint.relation} is not present")
    if constraint.kind == .check then
      let some source := constraint.expression
        | throw (.malformedIR s!"constraint {constraint.name}"
            "check has no normalized source expression")
      let some expression := constraint.localExpression
        | throw (.malformedIR s!"constraint {constraint.name}"
            "check has no typed local expression")
      match Pgx.Codegen.ConstraintParser.parseTableCheck relation db.enums db.domains source with
      | .error diagnostic =>
          throw (.unsupportedConstraint s!"constraint {constraint.name}" (toString diagnostic))
      | .ok parsed =>
          unless parsed.validated == constraint.validated do
            throw (.malformedIR s!"constraint {constraint.name}"
              "NOT VALID suffix differs from catalog validation metadata")
          unless parsed.expression == expression do
            throw (.malformedIR s!"constraint {constraint.name}"
              "typed expression differs from reparsing its normalized source")
    else if constraint.localExpression.isSome then
      throw (.malformedIR s!"constraint {constraint.name}"
        "only a row-local check may carry a typed local expression")

private def validateLogicalColumn (db : Pgx.DatabaseIR) (queryName : String)
    (column : Pgx.QueryColumnIR) : Except CodegenError Unit := do
  let some logical := column.logicalType | pure ()
  let some _ := db.domain? logical.key
    | throw (.malformedIR s!"result {queryName}.{column.name}"
        "logicalType is not a declared domain")
  let some origin := column.origin
    | throw (.malformedIR s!"result {queryName}.{column.name}"
        "a logical domain requires direct column provenance")
  let some relation := relation? db origin.relation
    | throw (.malformedIR s!"result {queryName}.{column.name}"
        "logical origin relation is not present")
  let candidates := relation.columns.filter (fun source => source.name == origin.name)
  unless candidates.size == 1 && candidates[0]!.ty == logical do
    throw (.malformedIR s!"result {queryName}.{column.name}"
      "logical type differs from its source relation column")
  unless (← wireBaseRef db logical) == column.ty do
    throw (.malformedIR s!"result {queryName}.{column.name}"
      "wire type differs from the logical domain's fully unwrapped base")

private def validateIR (db : Pgx.DatabaseIR) : Except CodegenError Unit := do
  for value in db.enums do
    unless value.key.kind == .enum do
      throw (.malformedIR s!"enum {value.key}" "its TypeKey kind is not enum")
    if let some label := firstDuplicate? value.labels then
      throw (.malformedIR s!"enum {value.key}" s!"duplicate label {repr label}")
  for value in db.domains do
    unless value.key.kind == .domain do
      throw (.malformedIR s!"domain {value.key}" "its TypeKey kind is not domain")
    validateRefinementTypmod db value.base s!"domain {value.key}"
    validateDomainConstraints db value
  let declaredTypeKeys := db.enums.map (·.key) ++ db.domains.map (·.key)
  if let some key := firstDuplicate? declaredTypeKeys then throw (.duplicateType key)
  if let some key := firstDuplicate? (db.typeOverrides.map (·.key)) then throw (.duplicateType key)
  for value in db.typeOverrides do checkOverride value

  if let some key := firstDuplicate? (db.relations.map (·.key)) then
    throw (.duplicateRelation key)
  for relation in db.relations do
    if let some name := firstDuplicate? (relation.columns.map (·.name)) then
      throw (.malformedIR s!"relation {relation.key}" s!"duplicate column {repr name}")
    for column in relation.columns do
      checkTypeSupported db column.ty.key s!"column {relation.key}.{column.name}"
      let base ← wireBaseRef db column.ty
      validateRefinementTypmod db base s!"column {relation.key}.{column.name}"

  validateRelationConstraints db

  if let some name := firstDuplicate? (db.queries.map (·.name)) then
    throw (.duplicateQuery name)
  for query in db.queries do
    if query.name.trimAscii.toString.isEmpty then
      throw (.malformedIR "query" "generated Lean name is empty")
    if let some name := firstDuplicate? (query.params.map (·.name)) then
      throw (.malformedIR s!"query {query.name}" s!"duplicate parameter name {repr name}")
    if let some name := firstDuplicate? (query.columns.map (·.name)) then
      throw (.malformedIR s!"query {query.name}" s!"duplicate result name {repr name}")
    for i in [0:query.params.size] do
      unless query.params[i]!.position == i + 1 do
        throw (.malformedIR s!"query {query.name}"
          "parameter positions must be dense and start at one")
    if query.cardinality == .execute && !query.columns.isEmpty then
      throw (.malformedIR s!"query {query.name}"
        "execute cardinality cannot have result columns")
    if query.cardinality != .execute && query.columns.isEmpty then
      throw (.malformedIR s!"query {query.name}"
        "row-returning cardinality must have at least one result column")
    if let some relation := firstDuplicate? query.rowPreservedRelations then
      throw (.malformedIR s!"query {query.name}"
        s!"duplicate row-preserved relation {relation}")
    for key in query.rowPreservedRelations do
      unless (relation? db key).isSome do
        throw (.malformedIR s!"query {query.name}"
          s!"row-preserved relation {key} is not present")
      unless query.columns.any (fun column =>
          column.origin.map (fun origin => origin.relation == key) |>.getD false) do
        throw (.malformedIR s!"query {query.name}"
          s!"row-preserved relation {key} has no direct result column")
      if query.columns.any (fun column =>
          column.nullWidened &&
            (column.origin.map (fun origin => origin.relation == key) |>.getD false)) then
        throw (.malformedIR s!"query {query.name}"
          s!"row-preserved relation {key} has a null-widened result")
    for param in query.params do
      checkTypeSupported db param.ty.key s!"parameter {query.name}.${param.position}"
    for column in query.columns do
      if column.name.isEmpty then
        throw (.malformedIR s!"query {query.name}" "result column name is empty")
      if column.nullWidened && !column.nullable then
        throw (.malformedIR s!"result {query.name}.{column.name}"
          "a null-widened result must be nullable")
      checkTypeSupported db column.ty.key s!"result {query.name}.{column.name}"
      if let some logical := column.logicalType then
        checkTypeSupported db logical.key s!"logical result {query.name}.{column.name}"
      validateLogicalColumn db query.name column
      let base ← wireBaseRef db (column.logicalType.getD column.ty)
      validateRefinementTypmod db base s!"result {query.name}.{column.name}"
    let planned := Pgx.Codegen.Projection.planQuery db.relations db.constraints query
    unless planned.localConstraints == query.localConstraints do
      throw (.malformedIR s!"query {query.name}"
        "local constraints differ from the direct-projection plan")

  for value in db.enums do checkTypeSupported db value.key s!"enum {value.key}"
  for value in db.domains do
    checkTypeSupported db value.key s!"domain {value.key}"

private def namedType? (plan : NamingPlan) (key : Pgx.TypeKey) : Option NamedType :=
  plan.types.find? (fun value => value.key == key)

private def resolveTypeUse (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (key : Pgx.TypeKey) : Except CodegenError TypeUse := do
  match db.typeOverride? key with
  | some value => pure { leanType := value.leanType, codec := some value.codec }
  | none =>
      match Pgx.builtinTypeMapping? key with
      | some value => pure { leanType := value.leanType }
      | none =>
          match namedType? plan key with
          | some value => pure { leanType := value.leanType, codec := some value.codec }
          | none => throw (.unsupportedType key "generated type lookup")

private def fieldType (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (ref : Pgx.TypeRef) (nullable : Bool) : Except CodegenError String := do
  let value ← resolveTypeUse plan db ref.key
  if nullable then pure s!"Option ({value.leanType})" else pure value.leanType

private def buildTypeNames (modulePrefix : String) (db : Pgx.DatabaseIR) : Array NamedType := Id.run do
  let mut scope : Scope := {}
  let mut values : Array NamedType := #[]
  for value in db.enums do
    if (db.typeOverride? value.key).isNone then
      let preferred := upperCamel value.key.schema ++ upperCamel value.key.name
      let (name, next) := scope.claim preferred
      scope := next
      let leanType := modulePrefix ++ ".Types." ++ name
      values := values.push { key := value.key, leanType, codec := leanType ++ ".codec" }
  for value in db.domains do
    if (db.typeOverride? value.key).isNone then
      let preferred := upperCamel value.key.schema ++ upperCamel value.key.name
      let (name, next) := scope.claim preferred
      scope := next
      let leanType := modulePrefix ++ ".Types." ++ name
      values := values.push { key := value.key, leanType, codec := leanType ++ ".codec" }
  return values

private def buildSchemas (db : Pgx.DatabaseIR) : Array NamedSchema := Id.run do
  let mut sourceNames : Array String := #[]
  for schema in db.schemas do sourceNames := pushUnique sourceNames schema.name
  for relation in db.relations do sourceNames := pushUnique sourceNames relation.key.schema
  sourceNames := sortStrings sourceNames
  let mut scope : Scope := {}
  let mut values : Array NamedSchema := #[]
  for source in sourceNames do
    let (leanName, next) := scope.claim (upperCamel source "Schema")
    scope := next
    values := values.push { source, leanName }
  return values

private def buildRelations (schemas : Array NamedSchema)
    (db : Pgx.DatabaseIR) : Array NamedRelation := Id.run do
  let mut values : Array NamedRelation := #[]
  for relation in db.relations do
    let schemaName := (schemas.find? (fun value => value.source == relation.key.schema)).map
      (·.leanName) |>.getD (upperCamel relation.key.schema "Schema")
    let used := values.filter (fun value => value.key.schema == relation.key.schema)
      |>.map (·.relationName)
    let scope : Scope := { used }
    let (relationName, _) := scope.claim (upperCamel relation.key.name "Relation")
    values := values.push { key := relation.key, schemaName, relationName }
  return values

private def buildQueries (db : Pgx.DatabaseIR) : Array NamedQuery := Id.run do
  let mut scope : Scope := {}
  let mut values : Array NamedQuery := #[]
  for query in db.queries do
    let (moduleName, next) := scope.claim (upperCamel query.name "Query")
    scope := next
    values := values.push { query, moduleName }
  return values

private def buildNamingPlan (modulePrefix : String)
    (db : Pgx.DatabaseIR) : Except CodegenError NamingPlan := do
  let (normalizedPrefix, prefixPath) ← normalizePrefix modulePrefix
  let types := buildTypeNames normalizedPrefix db
  let schemas := buildSchemas db
  pure {
    modulePrefix := normalizedPrefix
    prefixPath
    types
    schemas
    relations := buildRelations schemas db
    queries := buildQueries db
  }

private def domainDependencyPending (db : Pgx.DatabaseIR)
    (pending : Array Pgx.DomainIR) (domain : Pgx.DomainIR) : Bool :=
  (db.typeOverride? domain.base.key).isNone &&
    pending.any (fun candidate => candidate.key == domain.base.key)

private def orderDomainsAux (db : Pgx.DatabaseIR) (pending ready : Array Pgx.DomainIR) :
    Nat → Except CodegenError (Array Pgx.DomainIR)
  | 0 =>
      match pending[0]? with
      | some value => throw (.cyclicDomain value.key)
      | none => pure ready
  | fuel + 1 =>
      if pending.isEmpty then pure ready
      else
        let layer := pending.filter (fun value => !domainDependencyPending db pending value)
        if layer.isEmpty then
          throw (.cyclicDomain pending[0]!.key)
        else
          let rest := pending.filter (fun value => !layer.any (fun done => done.key == value.key))
          orderDomainsAux db rest (ready ++ layer) fuel

private def orderedGeneratedDomains (db : Pgx.DatabaseIR) :
    Except CodegenError (Array Pgx.DomainIR) :=
  let pending := db.domains.filter (fun value => (db.typeOverride? value.key).isNone)
  orderDomainsAux db pending #[] (pending.size + 1)

private def collectTypeKeys (db : Pgx.DatabaseIR) : Array Pgx.TypeKey := Id.run do
  let mut values : Array Pgx.TypeKey := #[]
  for value in db.enums do values := pushUnique values value.key
  for value in db.domains do
    values := pushUnique values value.key
    values := pushUnique values value.base.key
  for value in db.typeOverrides do values := pushUnique values value.key
  for relation in db.relations do
    for column in relation.columns do values := pushUnique values column.ty.key
  for query in db.queries do
    for param in query.params do values := pushUnique values param.ty.key
    for column in query.columns do
      values := pushUnique values column.ty.key
      if let some logical := column.logicalType then values := pushUnique values logical.key
  return sortTypeKeys values

private def allocatedNames (sources : Array String) (fallback : String) : Array String := Id.run do
  let mut scope : Scope := { used := #["mk"] }
  let mut names : Array String := #[]
  for source in sources do
    let (name, next) := scope.claim (lowerCamel source fallback)
    scope := next
    names := names.push name
  return names

private structure ExprBinding where
  sourceName : String
  access : String
  declared : Pgx.TypeRef
  storage : Pgx.TypeRef
  nullable : Bool
  deriving Inhabited

private structure ExprScope where
  columns : Array ExprBinding := #[]
  domainValue : Option ExprBinding := none

private structure CompiledValue where
  expression : String
  semanticType : String
  scalarType : Pgx.Constraint.ScalarType

private structure GeneratedCheck where
  name : String
  evaluate : String

private def semanticTypeName (context : String) : Pgx.Constraint.ScalarType →
    Except CodegenError String
  | { base := .boolean, .. } => pure "Bool"
  | { base := .int16, .. } | { base := .int32, .. } | { base := .int64, .. } =>
      pure "Int"
  | { base := .text, .. } | { base := .enumeration _, .. } => pure "String"
  | { base := .numeric, .. } =>
      throw (.unsupportedConstraint context
        "pg_catalog.numeric has no modeled exact local comparison semantics")

private partial def scalarizeStorageAux (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (ref : Pgx.TypeRef) (expression context : String) (seen : Array Pgx.TypeKey) :
    Except CodegenError String := do
  if seen.contains ref.key then throw (.cyclicDomain ref.key)
  if (db.typeOverride? ref.key).isSome then
    throw (.unsupportedConstraint context
      s!"type override {ref.key} has no local-refinement scalar adapter")
  match db.domain? ref.key with
  | some domain =>
      let some named := namedType? plan ref.key
        | throw (.unsupportedConstraint context
            s!"domain {ref.key} has no generated local validator")
      scalarizeStorageAux plan db domain.base
        s!"{named.leanType}.toBase ({expression})" context (seen.push ref.key)
  | none =>
      match db.enum? ref.key with
      | some _ =>
          let some named := namedType? plan ref.key
            | throw (.unsupportedConstraint context
                s!"enum {ref.key} has no generated label mapping")
          pure s!"{named.leanType}.toLabel ({expression})"
      | none =>
          if ref.key.schema != "pg_catalog" then
            throw (.unsupportedConstraint context
              s!"type {ref.key} has no local-refinement scalar adapter")
          else if ref.key.name == "bool" then pure expression
          else if ref.key.name == "int2" || ref.key.name == "int4" ||
              ref.key.name == "int8" then
            pure s!"({expression}).toInt"
          else if ref.key.name == "text" || ref.key.name == "varchar" ||
              ref.key.name == "bpchar" || ref.key.name == "name" ||
              ref.key.name == "char" then
            pure expression
          else
            throw (.unsupportedConstraint context
              s!"type {ref.key} has no local-refinement scalar adapter")

private def scalarizeStorage (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (ref : Pgx.TypeRef) (expression context : String) : Except CodegenError String :=
  scalarizeStorageAux plan db ref expression context #[]

private def findBinding (scope : ExprScope) (name context : String) :
    Except CodegenError ExprBinding := do
  let bindings := scope.columns.filter (fun binding => binding.sourceName == name)
  unless bindings.size == 1 do
    throw (.malformedIR context s!"column {repr name} does not resolve uniquely")
  pure bindings[0]!

private def optionValueExpression (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (binding : ExprBinding) (semanticType context : String) : Except CodegenError String := do
  let payload ← scalarizeStorage plan db binding.storage "present" context
  if binding.nullable then
    pure s!"({binding.access}).map (fun present => {payload})"
  else
    pure s!"(some ({← scalarizeStorage plan db binding.storage binding.access context}) : Option {semanticType})"

private partial def compileValueExpr (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (scope : ExprScope) (context : String) : Pgx.Constraint.ValueExpr →
    Except CodegenError CompiledValue
  | expression@(.column name ty nullable) => do
      let binding ← findBinding scope name context
      unless binding.declared == ty.declared && binding.nullable == nullable do
        throw (.malformedIR context s!"column annotation for {repr name} differs from its field")
      let semanticType ← semanticTypeName context ty
      let payload ← optionValueExpression plan db binding semanticType context
      pure {
        expression := s!"(.ok ({payload}) : Except Pgx.Constraint.EvaluationError (Option {semanticType}))"
        semanticType
        scalarType := expression.type
      }
  | expression@(.domainValue ty _) => do
      let some binding := scope.domainValue
        | throw (.malformedIR context "VALUE appears outside a domain constraint")
      unless binding.declared == ty.declared do
        throw (.malformedIR context "VALUE annotation differs from its domain")
      let semanticType ← semanticTypeName context ty
      let payload ← optionValueExpression plan db binding semanticType context
      pure {
        expression := s!"(.ok ({payload}) : Except Pgx.Constraint.EvaluationError (Option {semanticType}))"
        semanticType
        scalarType := expression.type
      }
  | expression@(.literal literal ty) => do
      let semanticType ← semanticTypeName context ty
      let payload ← match literal with
        | .null => pure s!"(none : Option {semanticType})"
        | .boolean value => pure s!"some ({boolExpr value})"
        | .integer value => pure s!"some ({value})"
        | .numeric _ =>
            throw (.unsupportedConstraint context
              "pg_catalog.numeric literals have no modeled exact local semantics")
        | .text value => pure s!"some ({stringLiteral value})"
        | .enumeration _ label => pure s!"some ({stringLiteral label})"
      pure {
        expression := s!"(.ok ({payload}) : Except Pgx.Constraint.EvaluationError (Option {semanticType}))"
        semanticType
        scalarType := expression.type
      }
  | expression@(.cast preservation value target) => do
      if preservation == .exactNumeric then
        throw (.unsupportedConstraint context
          "exact numeric casts have no modeled local semantics")
      let compiled ← compileValueExpr plan db scope context value
      let targetType ← semanticTypeName context target
      unless compiled.semanticType == targetType do
        throw (.malformedIR context "preserving cast changes its normalized semantic carrier")
      pure { compiled with scalarType := expression.type }
  | .neg .. =>
      throw (.unsupportedConstraint context
        "fixed-width unary negation requires modeled PostgreSQL overflow semantics")
  | .add .. | .sub .. =>
      throw (.unsupportedConstraint context
        "fixed-width arithmetic requires modeled PostgreSQL overflow semantics")
  | expression@(.charLength value _) => do
      let compiled ← compileValueExpr plan db scope context value
      unless compiled.semanticType == "String" do
        throw (.malformedIR context "char_length operand is not text")
      pure {
        expression := s!"({compiled.expression}).bind (fun value => Pgx.Constraint.liftNullable (fun present => .ok (Pgx.Constraint.charLength present)) value)"
        semanticType := "Int"
        scalarType := expression.type
      }
  | expression@(.btrim value _) => do
      let compiled ← compileValueExpr plan db scope context value
      unless compiled.semanticType == "String" do
        throw (.malformedIR context "btrim operand is not text")
      pure {
        expression := s!"({compiled.expression}).bind (fun value => Pgx.Constraint.liftNullable (fun present => .ok (Pgx.Constraint.btrim present)) value)"
        semanticType := "String"
        scalarType := expression.type
      }
  | expression@(.position substring string _) => do
      let left ← compileValueExpr plan db scope context substring
      let right ← compileValueExpr plan db scope context string
      unless left.semanticType == "String" && right.semanticType == "String" do
        throw (.malformedIR context "position operands are not text")
      pure {
        expression := s!"({left.expression}).bind (fun substring => ({right.expression}).bind (fun string => Pgx.Constraint.liftNullable₂ (fun needle haystack => .ok (Pgx.Constraint.position needle haystack)) substring string))"
        semanticType := "Int"
        scalarType := expression.type
      }

private def comparisonName : Pgx.Constraint.Comparison → String
  | .eq => "eq"
  | .ne => "ne"
  | .lt => "lt"
  | .le => "le"
  | .gt => "gt"
  | .ge => "ge"

private partial def compileTruthExpr (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (scope : ExprScope) (context : String) : Pgx.Constraint.TruthExpr →
    Except CodegenError String
  | .constant none => pure "(.ok .unknown)"
  | .constant (some true) => pure "(.ok .true)"
  | .constant (some false) => pure "(.ok .false)"
  | .fromBoolean value => do
      let compiled ← compileValueExpr plan db scope context value
      unless compiled.semanticType == "Bool" do
        throw (.malformedIR context "Boolean truth expression has a non-Boolean carrier")
      pure s!"({compiled.expression}).map Pgx.Constraint.SqlTruth.ofOptionBool"
  | .compare operator left right => do
      let left ← compileValueExpr plan db scope context left
      let right ← compileValueExpr plan db scope context right
      unless left.semanticType == right.semanticType do
        throw (.malformedIR context "comparison operands use different semantic carriers")
      let body ← match operator with
        | .eq => pure "Pgx.Constraint.equalNullable left right"
        | .ne => pure "Pgx.Constraint.notEqualNullable left right"
        | operator =>
            unless left.semanticType == "Int" do
              throw (.unsupportedConstraint context
                "only fixed-width integer ordering has modeled local semantics")
            pure s!"Pgx.Constraint.compareNullable .{comparisonName operator} left right"
      pure s!"({left.expression}).bind (fun left => ({right.expression}).map (fun right => {body}))"
  | .isNull value => do
      let compiled ← compileValueExpr plan db scope context value
      pure s!"({compiled.expression}).map Pgx.Constraint.SqlTruth.isNull"
  | .isNotNull value => do
      let compiled ← compileValueExpr plan db scope context value
      pure s!"({compiled.expression}).map Pgx.Constraint.SqlTruth.isNotNull"
  | .and left right => do
      let left ← compileTruthExpr plan db scope context left
      let right ← compileTruthExpr plan db scope context right
      pure s!"({left}).bind (fun left => ({right}).map (fun right => left.conjunction right))"
  | .or left right => do
      let left ← compileTruthExpr plan db scope context left
      let right ← compileTruthExpr plan db scope context right
      pure s!"({left}).bind (fun left => ({right}).map (fun right => left.disjunction right))"
  | .not value => do
      let value ← compileTruthExpr plan db scope context value
      pure s!"({value}).map Pgx.Constraint.SqlTruth.negate"

private def characterTypmodCheck? (ref : Pgx.TypeRef) (access : String)
    (nullable : Bool) (name : String) : Option GeneratedCheck :=
  if ref.key.schema == "pg_catalog" &&
      (ref.key.name == "varchar" || ref.key.name == "bpchar") && ref.typmod.isSome then
    let value := if nullable then access else s!"some ({access})"
    some {
      name
      evaluate := s!"Pgx.Constraint.evaluateCharacterTypmod ({optionExpr (ref.typmod.map toString)}) ({value})"
    }
  else none

private def emitValidator (dataType publicType : String)
    (checks : Array GeneratedCheck) : List String :=
  let checkExprs := checks.map fun check =>
    recordExpr s!"name := {stringLiteral check.name}, evaluate := fun value => {check.evaluate}"
  [
    s!"private def checks : List (Pgx.Constraint.Check {dataType}) :=",
    "  [" ++ commaSep checkExprs ++ "]",
    "",
    s!"def ValidPred (value : {dataType}) : Prop :=",
    "  Pgx.Constraint.Valid checks value",
    "",
    s!"instance (value : {dataType}) : Decidable (ValidPred value) :=",
    "  Pgx.Constraint.validDecidable checks value",
    "",
    "abbrev " ++ publicType ++ " := { value : " ++ dataType ++ " // ValidPred value }",
    "",
    s!"def validate (value : {dataType}) : Except Pgx.ConstraintViolation {publicType} :=",
    "  Pgx.Constraint.validate checks value",
    "",
    "theorem validate_sound {value : " ++ dataType ++ "} {refined : " ++ publicType ++ "} :",
    "    validate value = .ok refined → refined.val = value ∧ ValidPred value := by",
    "  exact Pgx.Constraint.validate_sound checks",
    "",
    "theorem validate_complete {value : " ++ dataType ++ "} :",
    s!"    ValidPred value → ∃ refined : {publicType}, validate value = .ok refined := by",
    "  exact Pgx.Constraint.validate_complete checks",
    ""
  ]

private def rawEncodeBody (use : TypeUse) : List String :=
  match use.codec with
  | some codec => [s!"  {codec}.encode resolved value"]
  | none => [
      "  pure {",
      s!"    format := Pg.PgEncode.format {use.leanType}",
      "    value := Pg.PgEncode.encode value",
      "  }"
    ]

private def rawDecodeBody (use : TypeUse) : List String :=
  match use.codec with
  | some codec => [s!"  {codec}.decode resolved format value"]
  | none => [
      s!"  match Pg.decodeValue (α := {use.leanType}) resolved.oid format value with",
      "  | .ok decoded => pure decoded",
      "  | .error message => throw (.decode message)"
    ]

private def emitEnum (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (value : Pgx.EnumIR) : Except CodegenError (List String) := do
  let some named := namedType? plan value.key
    | throw (.unsupportedType value.key "enum declaration")
  let localName := (named.leanType.splitOn ".").getLast!
  let reservedCases := #["mk", "codec", "descriptor", "toLabel", "ofLabel"]
  let mut scope : Scope := { used := reservedCases }
  let mut cases : Array String := #[]
  for label in value.labels do
    let (name, next) := scope.claim (lowerCamel label "value")
    scope := next
    cases := cases.push name
  let mut lines := [s!"inductive {localName} where"]
  for name in cases do lines := lines ++ [s!"  | {name}"]
  lines := lines ++ ["  deriving Repr, BEq, DecidableEq", "", s!"namespace {localName}", ""]
  lines := lines ++ [s!"def toLabel : {localName} → String"]
  for i in [0:value.labels.size] do
    lines := lines ++ [s!"  | .{cases[i]!} => {stringLiteral value.labels[i]!}"]
  lines := lines ++ ["", s!"def ofLabel? : String → Option {localName}"]
  for i in [0:value.labels.size] do
    lines := lines ++ [s!"  | {stringLiteral value.labels[i]!} => some .{cases[i]!}"]
  lines := lines ++ [
    "  | _ => none",
    "",
    "def descriptor : Pgx.Typed.StaticTypeDesc :=",
    s!"  {typeDescExpr db value.key}",
    "",
    s!"def codec : Pgx.Typed.ResolvedCodec {localName} where",
    "  expected := descriptor",
    "  encode _ value := pure { format := 0, value := some (toLabel value).toUTF8 }",
    "  decode _ format value := do",
    s!"    let label ← decodeEnumLabel {stringLiteral value.key.display} format value",
    "    match ofLabel? label with",
    "    | some decoded => pure decoded",
    s!"    | none => throw (.decode ({stringLiteral ("unknown enum label for " ++ value.key.display ++ ": ")} ++ label))",
    "",
    s!"end {localName}",
    ""
  ]
  pure lines

private def emitDomain (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (value : Pgx.DomainIR) : Except CodegenError (List String) := do
  let some named := namedType? plan value.key
    | throw (.unsupportedType value.key "domain declaration")
  let localName := (named.leanType.splitOn ".").getLast!
  let base ← resolveTypeUse plan db value.base.key
  let context := s!"domain {value.key}"
  let scope : ExprScope := {
    domainValue := some {
      sourceName := "VALUE"
      access := "value.toBase"
      declared := { key := value.key }
      storage := value.base
      nullable := false
    }
  }
  let mut checks : Array GeneratedCheck := #[]
  for constraint in value.localConstraints do
    checks := checks.push {
      name := constraint.name
      evaluate := ← compileTruthExpr plan db scope
        s!"{context} constraint {constraint.name}" constraint.expression
    }
  if let some check := characterTypmodCheck? value.base "value.toBase" false
      s!"{value.key.display} character type modifier" then
    checks := checks.push check
  let mut lines := [
    s!"namespace {localName}",
    "",
    "structure Data where",
    s!"  toBase : {base.leanType}",
    ""
  ]
  lines := lines ++ emitValidator "Data" "Value" checks
  lines := lines ++ [
    s!"def toBase (value : Value) : {base.leanType} := value.val.toBase",
    "",
    "def descriptor : Pgx.Typed.StaticTypeDesc :=",
    s!"  {typeDescExpr db value.key}",
    "",
    s!"private def encodeBase (resolved : Pgx.Typed.ResolvedType) (value : {base.leanType}) :",
    "    Except Pgx.Typed.Error Pgx.Typed.EncodedValue := do",
    "  let _ := resolved"
  ]
  lines := lines ++ rawEncodeBody base
  lines := lines ++ [
    "",
    s!"private def decodeBase (resolved : Pgx.Typed.ResolvedType) (format : UInt16)",
    s!"    (value : Option ByteArray) : Except Pgx.Typed.Error {base.leanType} := do"
  ]
  lines := lines ++ rawDecodeBody base
  lines := lines ++ [
    "",
    s!"def codec : Pgx.Typed.ResolvedCodec Value where",
    "  expected := descriptor",
    "  encode resolved value := encodeBase resolved (toBase value)",
    "  decode resolved format value := do",
    "    let decoded ← decodeBase resolved format value",
    "    match validate { toBase := decoded } with",
    "    | .ok refined => pure refined",
    "    | .error violation => throw (Pgx.Typed.Error.constraintViolation violation)",
    "",
    s!"end {localName}",
    "",
    s!"abbrev {localName} := {localName}.Value",
    ""
  ]
  pure lines

private def emitTypes (plan : NamingPlan) (db : Pgx.DatabaseIR) :
    Except CodegenError String := do
  let importModules := Id.run do
    let mut values : Array String := #[]
    for value in db.typeOverrides do
      if let some moduleName := value.importModule then
        if moduleName != "Pgx.Typed" then values := pushUnique values moduleName
    return sortStrings values
  let mut lines : List String := [generatedHeader]
  for moduleName in importModules do
    lines := lines ++ ["import " ++ moduleName]
  lines := lines ++ [
    "import Pgx.Constraint.Semantics",
    "import Pgx.Typed",
    "",
    s!"namespace {plan.modulePrefix}.Types",
    "",
    "private def decodeEnumLabel (typeName : String) (format : UInt16)",
    "    (value : Option ByteArray) : Except Pgx.Typed.Error String := do",
    "  unless format == 0 || format == 1 do",
    "    throw (.decode (\"unsupported wire format for enum \" ++ typeName))",
    "  let some bytes := value",
    "    | throw (.decode (\"unexpected NULL for enum \" ++ typeName))",
    "  let some label := String.fromUTF8? bytes",
    "    | throw (.decode (\"enum value is not UTF-8 for \" ++ typeName))",
    "  pure label",
    ""
  ]
  for value in db.enums do
    if (db.typeOverride? value.key).isNone then
      lines := lines ++ (← emitEnum plan db value)
  for value in ← orderedGeneratedDomains db do
    lines := lines ++ (← emitDomain plan db value)
  let descriptors := collectTypeKeys db |>.map (typeDescExpr db)
  lines := lines ++ [
    "def staticTypes : Array Pgx.Typed.StaticTypeDesc :=",
    s!"  {arrayExpr descriptors}",
    "",
    s!"end {plan.modulePrefix}.Types"
  ]
  pure (sourceText lines)

private def relationNames (plan : NamingPlan) (key : Pgx.RelationKey) :
    Except CodegenError (String × String) :=
  match plan.relations.find? (fun value => value.key == key) with
  | some value => pure (value.schemaName, value.relationName)
  | none => throw (.malformedIR s!"relation {key}" "missing generated name")

private def emitRelation (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (relation : Pgx.RelationIR) : Except CodegenError (List String) := do
  let (schemaName, relationName) ← relationNames plan relation.key
  let names := allocatedNames (relation.columns.map (·.name)) "column"
  let mut bindings : Array ExprBinding := #[]
  for i in [0:relation.columns.size] do
    let column := relation.columns[i]!
    bindings := bindings.push {
      sourceName := column.name
      access := s!"value.{names[i]!}"
      declared := column.ty
      storage := column.ty
      nullable := column.nullable
    }
  let scope : ExprScope := { columns := bindings }
  let mut checks : Array GeneratedCheck := #[]
  for constraint in db.constraints do
    if constraint.relation == relation.key && constraint.kind == .check then
      let some expression := constraint.localExpression
        | throw (.malformedIR s!"constraint {constraint.name}"
            "validated check has no typed local expression")
      checks := checks.push {
        name := constraint.name
        evaluate := ← compileTruthExpr plan db scope
          s!"relation {relation.key} constraint {constraint.name}" expression
      }
  for i in [0:relation.columns.size] do
    let column := relation.columns[i]!
    if let some check := characterTypmodCheck? column.ty s!"value.{names[i]!}"
        column.nullable s!"{relation.key.display}.{column.name} character type modifier" then
      checks := checks.push check
  let mut lines := [s!"namespace {plan.modulePrefix}.Schema.{schemaName}.{relationName}", ""]
  lines := lines ++ ["structure Data where"]
  for i in [0:relation.columns.size] do
    let column := relation.columns[i]!
    lines := lines ++ [s!"  {names[i]!} : {← fieldType plan db column.ty column.nullable}"]
  lines := lines ++ [""]
  lines := lines ++ emitValidator "Data" "Row" checks
  lines := lines ++ [
    "def descriptor : Pgx.Typed.StaticRelationDesc :=",
    s!"  {staticRelationExpr relation}",
    "",
    s!"end {plan.modulePrefix}.Schema.{schemaName}.{relationName}",
    ""
  ]
  pure lines

private def serverMajorsExpr (db : Pgx.DatabaseIR) : String :=
  let majors := if db.supportedServerMajors.isEmpty then #[db.serverMajor]
    else db.supportedServerMajors
  arrayExpr (majors.map (fun major => toString major))

private def emitSchema (plan : NamingPlan) (db : Pgx.DatabaseIR) :
    Except CodegenError String := do
  let mut lines : List String := [
    generatedHeader,
    s!"import {plan.modulePrefix}.Types",
    "",
  ]
  for relation in db.relations do lines := lines ++ (← emitRelation plan db relation)
  let relationDescriptors ← db.relations.mapM fun relation => do
    let (schemaName, relationName) ← relationNames plan relation.key
    pure s!"{plan.modulePrefix}.Schema.{schemaName}.{relationName}.descriptor"
  lines := lines ++ [
    s!"namespace {plan.modulePrefix}",
    "",
    "def database : Pgx.Typed.DatabaseDesc := {",
    s!"  canonicalMajor := {db.serverMajor}",
    s!"  serverMajors := {serverMajorsExpr db}",
    s!"  session := {sessionExpr db.session}",
    s!"  types := {plan.modulePrefix}.Types.staticTypes",
    s!"  relations := {arrayExpr relationDescriptors}",
    s!"  schemaHash := {stringLiteral db.contractHash}",
    s!"  contractHash := {stringLiteral db.contractHash}",
    "}",
    "",
    "def attach (conn : Pg.Connection) :",
    "    Std.Async.Async (Except Pgx.Typed.Error (Pgx.Typed.CheckedConnection database)) :=",
    "  Pgx.Typed.attach database conn",
    "",
    s!"end {plan.modulePrefix}"
  ]
  pure (sourceText lines)

private def emitConstraints (plan : NamingPlan) (db : Pgx.DatabaseIR) : String :=
  sourceText [
    generatedHeader,
    s!"import {plan.modulePrefix}.Schema",
    "",
    s!"namespace {plan.modulePrefix}.Constraints",
    "",
    "def all : Array Pgx.ConstraintIR :=",
    s!"  {arrayExpr (db.constraints.map constraintExpr)}",
    "",
    "def indexes : Array Pgx.IndexIR :=",
    s!"  {arrayExpr (db.indexes.map indexExpr)}",
    "",
    s!"end {plan.modulePrefix}.Constraints"
  ]

private def codecExpr (use : TypeUse) (nullable : Bool) : Option String :=
  use.codec.map fun codec => if nullable then s!"({codec}).option" else codec

private def encodeValueExpr (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (ref : Pgx.TypeRef) (nullable : Bool) (value : String) : Except CodegenError String := do
  let use ← resolveTypeUse plan db ref.key
  match codecExpr use nullable with
  | some codec =>
      pure s!"Pgx.Typed.encodeResolved {codec} catalog ({typeRefExpr ref}) {value}"
  | none => pure s!"Pgx.Typed.encodeBuiltin catalog ({typeRefExpr ref}) {value}"

private def decodeValueExpr (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (ref : Pgx.TypeRef) (nullable : Bool) (index : Nat) : Except CodegenError String := do
  let use ← resolveTypeUse plan db ref.key
  let args := s!"catalog ({typeRefExpr ref}) columns[{index}]!.format values[{index}]!"
  match codecExpr use nullable with
  | some codec => pure s!"Pgx.Typed.decodeResolved {codec} {args}"
  | none => pure s!"Pgx.Typed.decodeBuiltin {args}"

private partial def domainChainAux (db : Pgx.DatabaseIR) (key : Pgx.TypeKey)
    (seen : Array Pgx.TypeKey) : Except CodegenError (Array Pgx.DomainIR) := do
  if seen.contains key then throw (.cyclicDomain key)
  let some domain := db.domain? key
    | throw (.malformedIR s!"logical type {key}" "expected a declared domain")
  if (db.typeOverride? key).isSome then
    throw (.unsupportedConstraint s!"logical type {key}"
      "a type override has no generated proof-producing domain validator")
  match db.domain? domain.base.key with
  | none => pure #[domain]
  | some _ =>
      pure (#[domain] ++ (← domainChainAux db domain.base.key (seen.push key)))

private def domainChain (db : Pgx.DatabaseIR) (key : Pgx.TypeKey) :
    Except CodegenError (Array Pgx.DomainIR) :=
  domainChainAux db key #[]

private def refineDomainExpression (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (logical : Pgx.TypeRef) (wireValue context : String) : Except CodegenError String := do
  let chain ← domainChain db logical.key
  let mut lines : List String := ["(do"]
  let mut previous := wireValue
  let mut index := 0
  for domain in chain.reverse do
    let some named := namedType? plan domain.key
      | throw (.unsupportedConstraint context
          s!"domain {domain.key} has no generated validator")
    let refined := s!"refined{index}"
    lines := lines ++ [
      "  let " ++ refined ++ " ← match " ++ named.leanType ++
        ".validate { toBase := " ++ previous ++ " } with",
      "    | .ok accepted => pure accepted",
      "    | .error violation => throw (Pgx.Typed.Error.constraintViolation violation)"
    ]
    previous := refined
    index := index + 1
  lines := lines ++ [s!"  pure {previous})"]
  pure (String.intercalate "\n" lines)

private def refineLogicalColumnExpression (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (column : Pgx.QueryColumnIR) (wireValue context : String) : Except CodegenError String := do
  let some logical := column.logicalType | pure wireValue
  if column.nullable then
    let refined ← refineDomainExpression plan db logical "present" context
    pure <| String.intercalate "\n" [
      "(do",
      s!"  match {wireValue} with",
      "  | none => pure none",
      "  | some present => some <$> " ++ refined,
      ")"
    ]
  else
    refineDomainExpression plan db logical wireValue context

private def cardinalityName : Pgx.Cardinality → String
  | .execute => "execute"
  | .exactlyOne => "exactlyOne"
  | .zeroOrOne => "zeroOrOne"
  | .many => "many"

private def cardinalityResult : Pgx.Cardinality → String
  | .execute => "Pgx.Typed.CommandResult"
  | .exactlyOne => "Row"
  | .zeroOrOne => "Option Row"
  | .many => "Array Row"

private def cardinalityRunner : Pgx.Cardinality → String
  | .execute => "execute"
  | .exactlyOne => "fetchOne"
  | .zeroOrOne => "fetchOptional"
  | .many => "fetchMany"

private def emitQuery (plan : NamingPlan) (db : Pgx.DatabaseIR)
    (named : NamedQuery) : Except CodegenError String := do
  let query := named.query
  let paramNames := allocatedNames (query.params.map (·.name)) "param"
  let columnNames := allocatedNames (query.columns.map (·.name)) "column"
  let namespaceName := plan.modulePrefix ++ ".Queries." ++ named.moduleName
  let mut bindings : Array ExprBinding := #[]
  for i in [0:query.columns.size] do
    let column := query.columns[i]!
    let logical := column.logicalType.getD column.ty
    bindings := bindings.push {
      sourceName := column.name
      access := s!"value.{columnNames[i]!}"
      declared := logical
      storage := logical
      nullable := column.nullable
    }
  let scope : ExprScope := { columns := bindings }
  let mut checks : Array GeneratedCheck := #[]
  for constraint in query.localConstraints do
    checks := checks.push {
      name := constraint.name
      evaluate := ← compileTruthExpr plan db scope
        s!"query {query.name} constraint {constraint.name}" constraint.expression
    }
  for i in [0:query.columns.size] do
    let column := query.columns[i]!
    if column.logicalType.isNone then
      if let some check := characterTypmodCheck? column.ty s!"value.{columnNames[i]!}"
          column.nullable s!"query {query.name}.{column.name} character type modifier" then
        checks := checks.push check
  let mut lines : List String := [
    generatedHeader,
    s!"import {plan.modulePrefix}.Schema",
    "",
    s!"namespace {namespaceName}",
    "",
    "structure Params where"
  ]
  for i in [0:query.params.size] do
    let param := query.params[i]!
    lines := lines ++ [s!"  {paramNames[i]!} : {← fieldType plan db param.ty param.nullable}"]
  lines := lines ++ ["", "structure RowData where"]
  for i in [0:query.columns.size] do
    let column := query.columns[i]!
    let logical := column.logicalType.getD column.ty
    lines := lines ++ [s!"  {columnNames[i]!} : {← fieldType plan db logical column.nullable}"]
  lines := lines ++ [""]
  lines := lines ++ emitValidator "RowData" "Row" checks
  lines := lines ++ [
    "private def encodeParams",
    s!"    (catalog : Pgx.Typed.ResolvedCatalog {plan.modulePrefix}.database)",
    "    (params : Params) : Except Pgx.Typed.Error Pgx.Typed.EncodedParams := do",
    "  let _ := catalog",
    "  let _ := params"
  ]
  let mut encodedNames : Array String := #[]
  for i in [0:query.params.size] do
    let encodedName := s!"encoded{i}"
    encodedNames := encodedNames.push encodedName
    lines := lines ++ [s!"  let {encodedName} ← {← encodeValueExpr plan db query.params[i]!.ty query.params[i]!.nullable s!"params.{paramNames[i]!}"}"]
  lines := lines ++ [
    "  pure {",
    s!"    values := {arrayExpr (encodedNames.map (· ++ ".value"))}",
    s!"    formats := {arrayExpr (encodedNames.map (· ++ ".format"))}",
    "  }",
    "",
    "private def decodeRow",
    s!"    (catalog : Pgx.Typed.ResolvedCatalog {plan.modulePrefix}.database)",
    "    (columns : Array Pg.Protocol.ColumnDesc)",
    "    (values : Array (Option ByteArray)) : Except Pgx.Typed.Error Row := do",
    "  let _ := catalog",
    s!"  unless columns.size == {query.columns.size} do",
    s!"    throw (.queryDrift \"generated decoder expected {query.columns.size} column descriptors\")",
    s!"  unless values.size == {query.columns.size} do",
    s!"    throw (.queryDrift \"generated decoder expected {query.columns.size} row values\")"
  ]
  let mut decodedNames : Array String := #[]
  for i in [0:query.columns.size] do
    let column := query.columns[i]!
    let wireName := s!"decodedWire{i}"
    lines := lines ++ [s!"  let {wireName} ← {← decodeValueExpr plan db column.ty column.nullable i}"]
    match column.logicalType with
    | none => decodedNames := decodedNames.push wireName
    | some _ =>
        let decodedName := s!"decoded{i}"
        decodedNames := decodedNames.push decodedName
        let refined ← refineLogicalColumnExpression plan db column wireName
          s!"query {query.name} result {column.name}"
        lines := lines ++ [s!"  let {decodedName} ← {refined}"]
  if query.columns.isEmpty then
    lines := lines ++ ["  let rowData : RowData := RowData.mk"]
  else
    let assignments := Array.range query.columns.size |>.map fun i =>
      columnNames[i]! ++ " := " ++ decodedNames[i]!
    lines := lines ++ ["  let rowData : RowData := { " ++ commaSep assignments ++ " }"]
  lines := lines ++ [
    "  match validate rowData with",
    "  | .ok refined => pure refined",
    "  | .error violation => throw (Pgx.Typed.Error.constraintViolation violation)"
  ]
  lines := lines ++ [
    "",
    "def spec :",
    s!"    Pgx.Typed.QuerySpec {plan.modulePrefix}.database Params Row .{cardinalityName query.cardinality} := " ++ "{",
    s!"  name := {stringLiteral query.name}",
    s!"  sql := {stringLiteral query.sql}",
    s!"  contractHash := {stringLiteral query.sqlHash}",
    s!"  params := {arrayExpr (query.params.map paramSpecExpr)}",
    s!"  columns := {arrayExpr (query.columns.map columnSpecExpr)}",
    "  encode := encodeParams",
    "  decode := decodeRow",
    "}",
    "",
    "def run",
    s!"    (conn : Pgx.Typed.CheckedConnection {plan.modulePrefix}.database)",
    s!"    (params : Params) : Std.Async.Async (Except Pgx.Typed.Error ({cardinalityResult query.cardinality})) :=",
    s!"  Pgx.Typed.{cardinalityRunner query.cardinality} spec conn params",
    "",
    s!"end {namespaceName}"
  ]
  pure (sourceText lines)

private def makeSource (path moduleName contents : String) : GeneratedSource :=
  { path, moduleName, contents }

private def emitRoot (plan : NamingPlan) : String :=
  let imports := [
    s!"import {plan.modulePrefix}.Types",
    s!"import {plan.modulePrefix}.Schema",
    s!"import {plan.modulePrefix}.Constraints"
  ] ++ plan.queries.toList.map (fun query =>
    s!"import {plan.modulePrefix}.Queries.{query.moduleName}")
  sourceText ([generatedHeader] ++ imports)

/-- Validate and deterministically emit the complete local-refinement API.

`modulePrefix` is normalized component-by-component to safe Lean module names;
the normalized value is returned in `GeneratedSources.modulePrefix` so a build
rule can diagnose an unexpected spelling if it chooses to require identity.
-/
def emitDatabase (modulePrefix : String) (database : Pgx.DatabaseIR) :
    Except CodegenError GeneratedSources := do
  let db := database.normalize
  validateIR db
  let plan ← buildNamingPlan modulePrefix db
  let typesModule := plan.modulePrefix ++ ".Types"
  let schemaModule := plan.modulePrefix ++ ".Schema"
  let constraintsModule := plan.modulePrefix ++ ".Constraints"
  let types := makeSource (plan.prefixPath ++ "/Types.lean") typesModule (← emitTypes plan db)
  let schema := makeSource (plan.prefixPath ++ "/Schema.lean") schemaModule (← emitSchema plan db)
  let constraints := makeSource (plan.prefixPath ++ "/Constraints.lean") constraintsModule
    (emitConstraints plan db)
  let mut queries : Array GeneratedSource := #[]
  for named in plan.queries do
    let moduleName := plan.modulePrefix ++ ".Queries." ++ named.moduleName
    queries := queries.push <| makeSource
      (plan.prefixPath ++ "/Queries/" ++ named.moduleName ++ ".lean")
      moduleName (← emitQuery plan db named)
  let root := makeSource (plan.prefixPath ++ ".lean") plan.modulePrefix (emitRoot plan)
  pure { modulePrefix := plan.modulePrefix, types, schema, constraints, queries, root }

end Pgx.Codegen
