"""Exact principal-theorem statements for lean-pgx's public runtime audit."""

PGX_PRINCIPAL_TYPES = {
    "Pgx.Constraint.validate_sound": "∀ {α : Type _} (checks : List (Pgx.Constraint.Check α)) {value : α} {refined : { candidate : α // Pgx.Constraint.Valid checks candidate }}, Pgx.Constraint.validate checks value = Except.ok refined → refined.val = value ∧ Pgx.Constraint.Valid checks value",
    "Pgx.Constraint.validate_complete": "∀ {α : Type _} (checks : List (Pgx.Constraint.Check α)) {value : α}, Pgx.Constraint.Valid checks value → ∃ refined, Pgx.Constraint.validate checks value = Except.ok refined",
    "Pgx.Logic.State.equivalent_refl": "∀ {schema : Pgx.Logic.Schema.{_, _}} (state : Pgx.Logic.State schema), Pgx.Logic.State.Equivalent state state",
    "Pgx.Logic.State.equivalent_symm": "∀ {schema : Pgx.Logic.Schema.{_, _}} {left right : Pgx.Logic.State schema}, Pgx.Logic.State.Equivalent left right → Pgx.Logic.State.Equivalent right left",
    "Pgx.Logic.State.equivalent_trans": "∀ {schema : Pgx.Logic.Schema.{_, _}} {first second third : Pgx.Logic.State schema}, Pgx.Logic.State.Equivalent first second → Pgx.Logic.State.Equivalent second third → Pgx.Logic.State.Equivalent first third",
    "Pgx.Typed.decodePlannedBuiltinSpanAt_eq_decodePlannedBuiltinSpan": "∀ {α : Type} [Pg.PgDecode α] [Pg.PgDecodeSpan α] (typeOid : UInt32) (format : UInt16) (row : Pg.Protocol.DataRowSpans) (index : Nat) (h : index < row.size), Pgx.Typed.decodePlannedBuiltinSpanAt typeOid format row index h = Pgx.Typed.decodePlannedBuiltinSpan typeOid format row index",
    "Pgx.Typed.PreparedRowDispatchBenchmark.decodeCandidate_eq_decodeReference": "∀ {db : Pgx.Typed.DatabaseDesc} {Params Row : Type} (spec : Pgx.Typed.QuerySpec db Params Row Pgx.Cardinality.many) (plan : Pgx.Typed.PreparedQueryPlan db) (catalog : Pgx.Typed.ResolvedCatalog db) (columns : Array Pg.Protocol.ColumnDesc) (rows : Array Pg.Protocol.DataRowSpans), Pgx.Typed.PreparedRowDispatchBenchmark.decodeCandidate spec plan catalog columns rows = Pgx.Typed.PreparedRowDispatchBenchmark.decodeReference spec plan catalog columns rows",
    "Pgx.Typed.PreparedSingleRowDispatchBenchmark.decodeCandidate_eq_decodeReference": "∀ {db : Pgx.Typed.DatabaseDesc} {Params Row : Type} {cardinality : Pgx.Cardinality} (spec : Pgx.Typed.QuerySpec db Params Row cardinality) (plan : Pgx.Typed.PreparedQueryPlan db) (catalog : Pgx.Typed.ResolvedCatalog db) (columns : Array Pg.Protocol.ColumnDesc) (values : Pg.Protocol.DataRowSpans), Pgx.Typed.PreparedSingleRowDispatchBenchmark.decodeCandidate spec plan catalog columns values = Pgx.Typed.PreparedSingleRowDispatchBenchmark.decodeReference spec plan catalog columns values",
}
