"""Pure lean-pgx tests."""

load("@rules_lean//lean:defs.bzl", "lean_test")

lean_test(
    name = "ir_test",
    srcs = ["IR.lean"],
    deps = ["//lean/Pgx:type_mapping"],
    strip_module_prefix = "lean",
)

lean_test(
    name = "typed_test",
    srcs = ["Typed.lean"],
    deps = ["//lean/Pgx/Typed:descriptors"],
    strip_module_prefix = "lean",
)
